#!/usr/bin/env sh

##########################################
#
#               INDEX
#       1. Spaces (Meh)
#       2. Window
#           - Navigation (ALT)
#           - Arrangement (ALT/OPTION + SHIFT)
#       3. Application Specific (CTRL, CMD)
#       4. Misc
# ########################################

##########################################
#           SPACES (MEH)
# ########################################
meh - 1 : yabai -m space --focus 1
meh - 2 : yabai -m space --focus 2
meh - 3 : yabai -m space --focus 3
meh - 4 : yabai -m space --focus 4
meh - 5 : yabai -m space --focus 5
meh - 6 : yabai -m space --focus 6
meh - 7 : yabai -m space --focus 7
meh - 8 : yabai -m space --focus 8
meh - 9 : yabai -m space --focus 9

# Moving Windows across spac
hyper - 1 : yabai -m window --space 1 --focus
hyper - 2 : yabai -m window --space 2 --focus
hyper - 3 : yabai -m window --space 3 --focus
hyper - 4 : yabai -m window --space 4 --focus
hyper - 5 : yabai -m window --space 5 --focus
hyper - 6 : yabai -m window --space 6 --focus
hyper - 7 : yabai -m window --space 7 --focus
hyper - 8 : yabai -m window --space 8 --focus
hyper - 9 : yabai -m window --space 9 --focus

hyper - n : yabai -m window --space next --focus
hyper - p : yabai -m window --space prev --focus
#
hyper - c : yabai -m space --create && yabai -m space --focus last
hyper - m : yabai -m space --create && yabai -m window --space last --focus 
hyper - x : yabai -m space --destroy

##########################################
#           WINDOW NAVIGATION (ALT)
# ########################################
cmd - tab : yabai -m space --focus recent
# maximize a window
alt - m : yabai -m window --toggle zoom-fullscreen

# change window focus within space
alt - j : yabai -m window --focus south
alt - k : yabai -m window --focus north
alt - h : yabai -m window --focus west
alt - l : yabai -m window --focus east

alt - b : yabai -m space --balance
alt - s : yabai -m space --padding abs:40:10:380:10
alt + shift - s : yabai -m space --padding abs:40:10:10:10

# -- Modifying the Layout --
alt - r : yabai -m space --rotate 270
alt - space : yabai -m window --toggle float

##########################################
#           WINDOW ARRANGMENT (ALT)
# ########################################
alt + shift - j : yabai -m window --swap south
alt + shift - k : yabai -m window --swap north
alt + shift - h : yabai -m window --swap west
alt + shift - l : yabai -m window --swap east

# increase window size
meh - k : yabai -m window --resize top:0:40
meh - l : yabai -m window --resize left:40:0

# decrease window size
meh - j : yabai -m window --resize top:0:-40
meh - h : yabai -m window --resize left:-40:0

##########################################
#           APPLICATION SPECIFIC (CTRL)
# ########################################
ctrl - j [
    "Microsoft Teams (work or school)": skhd -k "down"
    "Microsoft Outlook": skhd -k "ctrl - 0x1E"
]

ctrl - k [
    "Microsoft Teams (work or school)": skhd -k "up"
    "Microsoft Outlook": skhd -k "ctrl - 0x21"
]

ctrl - 0x21 [
    "Google Chrome": skhd -k "ctrl + shift - tab"
]

ctrl - 0x1E [
    "Google Chrome": skhd -k "ctrl - tab"
]

ctrl - n [
    "Google Chrome": skhd -k "down"
]

ctrl - p [
    "Google Chrome": skhd -k "up"
]

ctrl - h [
    "Google Chrome": skhd -k "cmd + shift - h"
]

ctrl - s [
    "Google Chrome": skhd -k "cmd - l"
]

ctrl - w [
    "Google Chrome": skhd -k "cmd - w"
]

ctrl - t [
    "Google Chrome": skhd -k "cmd - t"
]

ctrl - u [
    "Google Chrome": skhd -k "shift - space"
]

ctrl - d [
    "Google Chrome": skhd -k "space"
    "Microsoft Outlook": skhd -k "cmd - backspace"
]

##########################################
#           MISC (CTRL + ALT)
# ########################################
ctrl + alt - s : yabai --start-service
ctrl + alt - q : yabai --stop-service
ctrl + alt - r : yabai --restart-service

# change focus between external displays (left and right)
ctrl + alt - l : yabai -m display --focus next
ctrl + alt - h : yabai -m display --focus prev


